### ISSUE TITLE
Finish event register

### ISSUE THREAD

**Issue by WilliamDASILVA** [FightForSub/ffs-zera#26]
Finish the registration process for an event.
Missing:

- API endpoint (?)
- Locale translation

**Comment by Hartorn** [comment]
API Endpoints : 

* Endpoint inscription (sending only event id)
* Endpoint cancelling inscription
* Endpoint validating participant
* Endpoint myEvents

**Comment by Hartorn** [comment]
@WilliamDASILVA If you could take a look on the inscription script, would be great.
I would like some feedback on text, etc

**Comment by WilliamDASILVA** [comment]
@Hartorn 

In my opinion, it's not necessary to show the Twitch ID to the user. The Twitch name and his email is enough. Plus, it should be great to show the conditions required to join an event (affiliate, partner or none) before the validation.

![ffs2](https://user-images.githubusercontent.com/2766008/33169443-076469f4-d045-11e7-89e3-0cba715ea9d8.PNG)


Here is a mockup for suggestions that may be good to change:

- Remove the two lines about the reminder & unregister that don't belong to the register flow.
- As said, remove the Twitch ID, not pertinent
- Added a change account button, if needed but very optional.
- Add a rules reminder
- Use a custom event selection, instead of just a select box. In that box, we can add the required validations to join an event.
- Some wording changes:
  - Sélectionnez ci-dessous l’événement auquel vous souhaitez participer puis validez.
  - Après validation, vous allez recevoir un mail de confirmation sur l’adresse affichée dans le récapitulatif
  - Une fois votre inscription validée par les administrateurs, vous recevrez un second mail. Vous êtes alors inscrit !
- & some more visual updates.

Will take a look in the code himself asap

**Comment by Hartorn** [comment]
Indeed, it looks much better

Will try to take it in account this week end

Le 23 nov. 2017 12:02 PM, "William DA SILVA" <notifications@github.com> a
écrit :

**Comment by WilliamDASILVA** [comment]
@Hartorn Yup, the change button is not such a great idea finally. Since you're already signed on Twitch, even if you are signed out on our side, you'll reconnect with the same account.

If you do not feel confident doing thoses changes, I can make them if you want?

**Comment by Hartorn** [comment]
@WilliamDASILVA Please do if you have time, I will try to tackle the other issues

**Comment by Hartorn** [comment]
@WilliamDASILVA I've tried to do something looking alike with your design.
It's perfectible, if you want to have a look.
