### ISSUE TITLE
Order by not applied

### ISSUE THREAD

**Issue by WilliamDASILVA** [FightForSub/ffs-zera#52]
The `order_by` filter in the events view, on the first section of the page (`validated users`) is not applied, but instead is applied to the second part (`waiting for validation`).

**Comment by Hartorn** [comment]
@WilliamDASILVA Yep I tackled this, will push soon (finishing some changes for security)

**Comment by Hartorn** [comment]
Fixed in 19d7ba7e8ec3c367c99933549c5e4bf3b5191a51
